version: '3.8'

services:
  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27018:27017"
    command: ["mongod", "--bind_ip_all"]
    volumes:
      - ./data/mongo:/data/db

  backend:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    env_file:
      - ./.env
